// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import {Test} from "forge-std/Test.sol";
import {Poseidon2} from "../src/Poseidon2.sol";

/// @notice Cross-check Poseidon2 Solidity against Noir stdlib outputs.
///         Test vectors generated by: cd circuits/lib && nargo test test_vector --show-output
contract Poseidon2Test is Test {
    // ============================================================
    // hash_2 cross-check
    // ============================================================

    function test_hash2_zeros() public pure {
        uint256 result = Poseidon2.hash_2(0, 0);
        assertEq(result, 0x18dfb8dc9b82229cff974efefc8df78b1ce96d9d844236b496785c698bc6732e);
    }

    function test_hash2_small() public pure {
        uint256 result = Poseidon2.hash_2(1, 2);
        assertEq(result, 0x299bfccd7daf3c917e51291383929049ec0eaed800af245056cbf135f7dea636);
    }

    function test_hash2_medium() public pure {
        uint256 result = Poseidon2.hash_2(123456, 789012);
        assertEq(result, 0x08b548d9aae0bf589370553752f2b09b63515d792b68df9723e1b822a6259c16);
    }

    // ============================================================
    // hash_3 cross-check
    // ============================================================

    function test_hash3_zeros() public pure {
        // hash_3(0,0,0) == hash_2(0,0) because sponge rate=3, full absorb then squeeze
        uint256 result = Poseidon2.hash_3(0, 0, 0);
        assertEq(result, 0x18dfb8dc9b82229cff974efefc8df78b1ce96d9d844236b496785c698bc6732e);
    }

    function test_hash3_small() public pure {
        uint256 result = Poseidon2.hash_3(1, 2, 3);
        assertEq(result, 0x27c494c0c0bcb07fb9734dd1c34d066a3fb293fe170e9575adeceed1abb08c94);
    }

    // ============================================================
    // Merkle hash cross-check (hash_3 with DOMAIN_MERKLE=3)
    // ============================================================

    function test_merkle_zeros() public pure {
        // merkle(0, 0) = hash_3(0, 0, 3)
        uint256 result = Poseidon2.hash_3(0, 0, 3);
        assertEq(result, 0x01cbc853da7262c7ed2a8ef2101238ee9be2a7fda5303c0f00a21307d5330bd3);
    }

    function test_merkle_small() public pure {
        // merkle(1, 2) = hash_3(1, 2, 3) -- coincidence: DOMAIN_MERKLE=3
        uint256 result = Poseidon2.hash_3(1, 2, 3);
        assertEq(result, 0x27c494c0c0bcb07fb9734dd1c34d066a3fb293fe170e9575adeceed1abb08c94);
    }

    // ============================================================
    // hash_5 cross-check
    // ============================================================

    function test_hash5() public pure {
        uint256 result = Poseidon2.hash_5(1, 2, 3, 4, 5);
        assertEq(result, 0x086ebb4dbbd0b7426bb9eda8bee875e5d1fe720fb76bd858e5f2622f25b92e50);
    }

    // ============================================================
    // hash_6 cross-check
    // ============================================================

    function test_hash6() public pure {
        uint256 result = Poseidon2.hash_6(1, 2, 3, 4, 5, 6);
        // Noir output: 0x7cd0baf600e78e1e0e0acdc86dc93336578451c4badec9f3555a3c21c8be81
        // Pad to 32 bytes:
        assertEq(result, 0x007cd0baf600e78e1e0e0acdc86dc93336578451c4badec9f3555a3c21c8be81);
    }

    // ============================================================
    // Determinism
    // ============================================================

    function test_deterministic() public pure {
        uint256 a = Poseidon2.hash_2(42, 99);
        uint256 b = Poseidon2.hash_2(42, 99);
        assertEq(a, b);
    }

    // ============================================================
    // Sensitivity (different inputs -> different outputs)
    // ============================================================

    function test_sensitivity() public pure {
        uint256 a = Poseidon2.hash_2(1, 2);
        uint256 b = Poseidon2.hash_2(1, 3);
        assertTrue(a != b);
    }

    // ============================================================
    // Gas measurement
    // ============================================================

    function test_gas_hash2() public {
        uint256 gasBefore = gasleft();
        Poseidon2.hash_2(1, 2);
        uint256 gasUsed = gasBefore - gasleft();
        emit log_named_uint("hash_2 gas", gasUsed);
    }

    function test_gas_hash3() public {
        uint256 gasBefore = gasleft();
        Poseidon2.hash_3(1, 2, 3);
        uint256 gasUsed = gasBefore - gasleft();
        emit log_named_uint("hash_3 gas", gasUsed);
    }
}
