/**
 * Latent Circuit Test Vector Generator (Poseidon2)
 *
 * Generates valid Prover.toml inputs for the Latent Noir circuit.
 * All values are Field-level (quoted decimal strings).
 *
 * Usage:
 *   npx tsx scripts/generate_test_vectors.ts          # default (single vector -> circuits/Prover.toml)
 *   npx tsx scripts/generate_test_vectors.ts --e2e     # all scenarios -> circuits/test_vectors/
 */

import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import {
  computeNpk,
  computeCommitment,
  computeNullifier,
  computeComplianceHash,
  generateSparseProof,
  addressToField,
  TREE_DEPTH,
  REGISTRATION_DEPTH,
} from "./lib/crypto.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ============================================================
// Test Constants (all Field-level bigints)
// ============================================================

const SECRET = 42n;
const NSK_BOB = 12345n; // Bob's nullifier secret key
const NSK_ALICE = 99999n; // Alice's nsk (depositor, should NOT be able to withdraw)
const DEPOSITOR = addressToField("0xaAaAaAaaAaAaAaaAaAAAAAAAAaaaAaAaAaaAaaAa");
const RECIPIENT = addressToField("0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB");
const RECIPIENT_ALT = addressToField("0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC");

// ============================================================
// Prover.toml Generation
// ============================================================

interface ScenarioParams {
  secret: bigint;
  nsk: bigint;
  depositor: bigint;
  recipient: bigint;
  noteAmount: bigint;
  transferAmount: bigint;
  blockNumber: bigint;
  leafIndex: number;
  registrationLeafIndex?: number; // Default: 0
  // Overrides for negative scenarios
  overrideNpk?: bigint;
  overrideRoot?: bigint;
  overrideNullifier?: bigint;
  overridePublicAmount?: bigint;
  overrideComplianceHash?: bigint;
  overrideRegistrationRoot?: bigint;
}

function q(v: bigint): string {
  return `"${v.toString()}"`;
}

function generateProverToml(params: ScenarioParams): string {
  const {
    secret, nsk, depositor, recipient,
    noteAmount, transferAmount, blockNumber, leafIndex,
    registrationLeafIndex = 0,
    overrideNpk, overrideRoot, overrideNullifier,
    overridePublicAmount, overrideComplianceHash,
    overrideRegistrationRoot,
  } = params;

  const npk = computeNpk(nsk);
  const commitment = computeCommitment(secret, npk, noteAmount, blockNumber, depositor);
  const { root, siblings, pathIndices } = generateSparseProof(commitment, leafIndex, TREE_DEPTH);
  const nullifier = computeNullifier(secret, nsk);
  const complianceHash = computeComplianceHash(depositor, recipient, transferAmount, secret);

  // Registration tree: npk as leaf
  const regProof = generateSparseProof(npk, registrationLeafIndex, REGISTRATION_DEPTH);

  const finalNpk = overrideNpk ?? npk;
  const finalRoot = overrideRoot ?? root;
  const finalNullifier = overrideNullifier ?? nullifier;
  const finalPublicAmount = overridePublicAmount ?? transferAmount;
  const finalComplianceHash = overrideComplianceHash ?? complianceHash;
  const finalRegistrationRoot = overrideRegistrationRoot ?? regProof.root;

  return `# Latent Circuit - Poseidon2 Test Vector
# Generated by scripts/generate_test_vectors.ts

# Private inputs
secret = ${q(secret)}
nullifier_secret_key = ${q(nsk)}
nullifier_pub_key = ${q(finalNpk)}
merkle_siblings = [${siblings.map(s => q(s)).join(", ")}]
path_indices = [${pathIndices.join(", ")}]
note_amount = ${q(noteAmount)}
note_block_number = ${q(blockNumber)}
note_depositor = ${q(depositor)}
transfer_amount = ${q(transferAmount)}
registration_siblings = [${regProof.siblings.map(s => q(s)).join(", ")}]
registration_path_indices = [${regProof.pathIndices.join(", ")}]

# Public inputs
expected_root = ${q(finalRoot)}
nullifier = ${q(finalNullifier)}
amount = ${q(finalPublicAmount)}
recipient = ${q(recipient)}
compliance_hash = ${q(finalComplianceHash)}
expected_registration_root = ${q(finalRegistrationRoot)}
`;
}

// ============================================================
// Scenario Definitions
// ============================================================

interface Scenario {
  name: string;
  description: string;
  expectedResult: "pass" | "fail";
  failedConstraint?: string;
  params: ScenarioParams;
}

function buildScenarios(): Scenario[] {
  // Pre-compute values needed for negative scenarios
  const wrongNullifier = computeNullifier(99999n, NSK_BOB);
  const wrongNpk = computeNpk(77777n); // NPK from a different nsk

  return [
    // ---- Happy paths ----
    {
      name: "happy_full_amount",
      description: "Full amount transfer (transfer = note = 1,000,000)",
      expectedResult: "pass",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 1000000n,
        blockNumber: 12345678n, leafIndex: 0,
      },
    },
    {
      name: "happy_partial",
      description: "Partial transfer (500,000 of 1,000,000)",
      expectedResult: "pass",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 500000n,
        blockNumber: 12345678n, leafIndex: 0,
      },
    },
    {
      name: "happy_different_leaf",
      description: "Non-zero leaf index (leafIndex = 7)",
      expectedResult: "pass",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 500000n,
        blockNumber: 12345678n, leafIndex: 7,
      },
    },
    {
      name: "happy_min_amount",
      description: "Minimum transfer amount (1)",
      expectedResult: "pass",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 1n,
        blockNumber: 12345678n, leafIndex: 0,
      },
    },
    {
      name: "happy_recipient_binding",
      description: "Different recipient is correctly bound in compliance hash",
      expectedResult: "pass",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT_ALT,
        noteAmount: 1000000n, transferAmount: 500000n,
        blockNumber: 12345678n, leafIndex: 0,
      },
    },

    // ---- Negative scenarios ----
    {
      name: "fail_overflow",
      description: "Transfer exceeds note balance",
      expectedResult: "fail",
      failedConstraint: "Insufficient note balance",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 1000001n,
        blockNumber: 12345678n, leafIndex: 0,
      },
    },
    {
      name: "fail_wrong_root",
      description: "Merkle root mismatch (corrupted root)",
      expectedResult: "fail",
      failedConstraint: "Merkle root mismatch",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 500000n,
        blockNumber: 12345678n, leafIndex: 0,
        overrideRoot: 12345n,
      },
    },
    {
      name: "fail_wrong_nullifier",
      description: "Nullifier mismatch (wrong secret used for nullifier)",
      expectedResult: "fail",
      failedConstraint: "Nullifier mismatch",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 500000n,
        blockNumber: 12345678n, leafIndex: 0,
        overrideNullifier: wrongNullifier,
      },
    },
    {
      name: "fail_wrong_nsk",
      description: "NPK does not match NSK (wrong nsk provided)",
      expectedResult: "fail",
      failedConstraint: "NPK does not match NSK",
      params: {
        secret: SECRET, nsk: 77777n, // wrong nsk
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 500000n,
        blockNumber: 12345678n, leafIndex: 0,
        // Use correct NPK (from NSK_BOB) but wrong nsk -> NPK check fails
        overrideNpk: computeNpk(NSK_BOB),
      },
    },
    {
      name: "fail_alice_withdraw",
      description: "Alice (depositor) cannot withdraw - knows secret but not Bob's nsk",
      expectedResult: "fail",
      failedConstraint: "NPK does not match NSK",
      params: {
        secret: SECRET, nsk: NSK_ALICE, // Alice's nsk, not Bob's
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 500000n,
        blockNumber: 12345678n, leafIndex: 0,
        // Commitment was made with Bob's NPK, but Alice provides her own nsk
        // Her computed NPK won't match the one in commitment -> NPK check OR Merkle root fails
        overrideNpk: computeNpk(NSK_BOB), // use Bob's NPK for commitment, but Alice's nsk
      },
    },
    {
      name: "fail_amount_mismatch",
      description: "Public amount does not match transfer_amount",
      expectedResult: "fail",
      failedConstraint: "Public amount mismatch",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 500000n,
        blockNumber: 12345678n, leafIndex: 0,
        overridePublicAmount: 999999n,
      },
    },
    {
      name: "fail_compliance_hash_mismatch",
      description: "Compliance hash mismatch (tampered hash)",
      expectedResult: "fail",
      failedConstraint: "Compliance hash mismatch",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 500000n,
        blockNumber: 12345678n, leafIndex: 0,
        overrideComplianceHash: 12345n,
      },
    },
    {
      name: "fail_unregistered_npk",
      description: "NPK not in registration tree (wrong registration root)",
      expectedResult: "fail",
      failedConstraint: "NPK not in registration tree",
      params: {
        secret: SECRET, nsk: NSK_BOB,
        depositor: DEPOSITOR, recipient: RECIPIENT,
        noteAmount: 1000000n, transferAmount: 500000n,
        blockNumber: 12345678n, leafIndex: 0,
        overrideRegistrationRoot: 99999n,
      },
    },
  ];
}

// ============================================================
// Main
// ============================================================

const isE2E = process.argv.includes("--e2e");

if (isE2E) {
  const scenarios = buildScenarios();
  const baseDir = join(__dirname, "..", "circuits", "test_vectors");

  for (const scenario of scenarios) {
    const scenarioDir = join(baseDir, scenario.name);
    mkdirSync(scenarioDir, { recursive: true });

    const toml = generateProverToml(scenario.params);
    writeFileSync(join(scenarioDir, "Prover.toml"), toml);
  }

  // Write manifest
  const manifest = scenarios.map((s) => ({
    name: s.name,
    description: s.description,
    expectedResult: s.expectedResult,
    failedConstraint: s.failedConstraint ?? null,
  }));
  writeFileSync(join(baseDir, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");

  console.log(`Generated ${scenarios.length} test vectors in ${baseDir}`);
  for (const s of scenarios) {
    const icon = s.expectedResult === "pass" ? "+" : "-";
    console.log(`  [${icon}] ${s.name}: ${s.description}`);
  }
} else {
  // Default mode: single vector -> circuits/Prover.toml
  const params: ScenarioParams = {
    secret: SECRET, nsk: NSK_BOB,
    depositor: DEPOSITOR, recipient: RECIPIENT,
    noteAmount: 1000000n, transferAmount: 500000n,
    blockNumber: 12345678n, leafIndex: 0,
  };

  const toml = generateProverToml(params);

  const npk = computeNpk(NSK_BOB);
  const commitment = computeCommitment(SECRET, npk, 1000000n, 12345678n, DEPOSITOR);
  const nullifier = computeNullifier(SECRET, NSK_BOB);
  const { root } = generateSparseProof(commitment, 0, TREE_DEPTH);
  const complianceHash = computeComplianceHash(DEPOSITOR, RECIPIENT, 500000n, SECRET);
  const { root: regRoot } = generateSparseProof(npk, 0, REGISTRATION_DEPTH);

  console.log("=== Latent Circuit Test Vectors (Poseidon2) ===");
  console.log(`NPK:             ${npk}`);
  console.log(`Commitment:      ${commitment}`);
  console.log(`Nullifier:       ${nullifier}`);
  console.log(`Root:            ${root}`);
  console.log(`Compliance Hash: ${complianceHash}`);
  console.log(`Reg Root:        ${regRoot}`);
  console.log();

  const outputPath = join(__dirname, "..", "circuits", "Prover.toml");
  writeFileSync(outputPath, toml);
  console.log(`Prover.toml written to: ${outputPath}`);
}
